name: PromoterArchitecturePipeline
channels:
  - r
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.3=py_1
  - argcomplete=1.12.1=pyh9f0ad1d_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py37h8f50634_1
  - astroid=2.4.2=py37hc8dfbb8_1
  - async_generator=1.10=py_0
  - atk=2.36.0=2
  - atk-1.0=2.36.0=h516909a_2
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bcbiogff=0.6.6=pyh864c0ab_2
  - bedops=2.4.39=hc9558a2_0
  - bedtools=2.29.2=hc088bd4_0
  - binutils_impl_linux-64=2.35=h18a2f87_9
  - binutils_linux-64=2.35=heab0d09_28
  - bioconductor-annotationdbi=1.48.0=r36_0
  - bioconductor-biobase=2.46.0=r36h516909a_0
  - bioconductor-biocgenerics=0.32.0=r36_0
  - bioconductor-biocparallel=1.20.0=r36he1b5a44_0
  - bioconductor-clusterprofiler=3.14.0=r36_0
  - bioconductor-do.db=2.9=r36_7
  - bioconductor-dose=3.12.0=r36_0
  - bioconductor-enrichplot=1.6.0=r36_0
  - bioconductor-fgsea=1.12.0=r36he1b5a44_0
  - bioconductor-go.db=3.10.0=r36_0
  - bioconductor-gosemsim=2.12.0=r36he1b5a44_0
  - bioconductor-iranges=2.20.0=r36h516909a_0
  - bioconductor-org.at.tair.db=3.10.0=r36_0
  - bioconductor-qvalue=2.18.0=r36_1
  - bioconductor-s4vectors=0.24.0=r36h516909a_0
  - biopython=1.77=py37h8f50634_0
  - black=20.8b1=py_1
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37h8f50634_1000
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.11.8=ha878542_0
  - cachecontrol=0.12.6=py_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.11.8=py37h89c1867_0
  - cffi=1.14.3=py37h2b28604_0
  - cfgv=3.2.0=py_0
  - chardet=3.0.4=py37hc8dfbb8_1007
  - click=7.1.2=pyh9f0ad1d_0
  - configargparse=1.2.3=pyh9f0ad1d_0
  - cryptography=3.1.1=py37hb09aad4_0
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - cyrus-sasl=2.1.27=h063b49f_1
  - cython=0.29.21=py37h3340039_0
  - dataclasses=0.7=pyhb2cacf7_7
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distlib=0.3.1=pyh9f0ad1d_0
  - editdistance=0.5.3=py37h3340039_2
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - filelock=3.0.12=pyh9f0ad1d_0
  - flake8=3.8.4=py_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h1056068_1002
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.2=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - gcc_impl_linux-64=7.5.0=hdb87b24_16
  - gcc_linux-64=7.5.0=hf34d7eb_28
  - gdk-pixbuf=2.38.2=h3f25603_4
  - gettext=0.19.8.1=hc5be6a0_1002
  - gffutils=0.10.1=pyh864c0ab_1
  - gfortran_impl_linux-64=7.5.0=h1104b78_16
  - gfortran_linux-64=7.5.0=ha781d05_28
  - giflib=5.2.1=h516909a_2
  - git=2.29.2=pl5320h78be0e9_1
  - git-lfs=2.11.0=0
  - glib=2.66.0=h0dae87d_0
  - gmp=6.2.0=he1b5a44_2
  - goatools=1.0.6=pyh864c0ab_1
  - gobject-introspection=1.66.0=py37h619baee_0
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.42.3=h6939c30_1
  - gsl=2.6=h294904e_0
  - gtk2=2.24.32=h194ddfc_3
  - gts=0.7.6=h08bb679_0
  - gxx_impl_linux-64=7.5.0=h1104b78_16
  - gxx_linux-64=7.5.0=ha781d05_28
  - harfbuzz=2.7.2=hee91db6_0
  - hdmedians=0.14.1=py37h161383b_0
  - htslib=1.10.2=hd3b49d5_1
  - icu=67.1=he1b5a44_0
  - identify=1.5.10=pyhd3deb0d_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py37hc8dfbb8_0
  - importlib_metadata=2.0.0=0
  - iniconfig=1.0.1=pyh9f0ad1d_0
  - ipykernel=5.3.4=py37h43977f1_0
  - ipython=7.18.1=py37hc6149b9_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.6.4=py_0
  - jedi=0.17.2=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.7=py_0
  - jupyter_conda=3.4.0=pyh9f0ad1d_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterlab=2.2.8=py_0
  - jupyterlab-plotly-extension=1.0.0=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - kiwisolver=1.2.0=py37h99015e2_0
  - krb5=1.17.1=hfafb76e_3
  - lazy-object-proxy=1.4.3=py37h8f50634_2
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-devel_linux-64=7.5.0=h42c25f5_16
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libntlm=1.4=h516909a_1002
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libprotobuf=3.12.4=h8b12597_0
  - libsodium=1.0.18=h516909a_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-devel_linux-64=7.5.0=h4084dd6_16
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libtool=2.4.6=h516909a_1005
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.40.0=h516909a_0
  - libwebp=1.1.0=h56121f0_4
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - littleutils=0.2.2=py_0
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.2=he1b5a44_3
  - make=4.3=h516909a_0
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py37hd478181_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h8f50634_1001
  - more-itertools=8.5.0=py_0
  - mpfr=4.0.2=he80fd80_1
  - mpmath=1.1.0=py_0
  - msgpack-python=1.0.0=py37h99015e2_1
  - mypy_extensions=0.4.3=py37hc8dfbb8_2
  - mysql=8.0.21=0
  - mysql-client=8.0.21=hfbb26de_0
  - mysql-common=8.0.21=0
  - mysql-devel=8.0.21=0
  - mysql-libs=8.0.21=h43e1182_0
  - mysql-server=8.0.21=hba0ff14_0
  - natsort=7.0.1=py_0
  - nb_conda_kernels=2.2.4=py37hc8dfbb8_0
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.6=py37hc8dfbb8_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he1b5a44_1
  - nest-asyncio=1.4.1=py_0
  - networkx=2.5=py_0
  - nodeenv=1.5.0=pyh9f0ad1d_0
  - nodejs=14.13.0=h568c755_0
  - notebook=6.1.4=py37hc8dfbb8_0
  - numpy=1.19.1=py37h7ea13bd_2
  - olefile=0.46=py_0
  - openjdk=11.0.1=hacce0ff_1021
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1h=h516909a_0
  - ordered-set=4.0.2=py_0
  - outdated=0.2.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py37h0da4684_0
  - pandas-flavor=0.2.0=py_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=h7062337_4
  - parso=0.7.1=pyh9f0ad1d_0
  - pathspec=0.8.1=pyhd3deb0d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.2.0=py37h718be6c_1
  - pingouin=0.3.7=py_0
  - pip=20.2.3=py_0
  - pixman=0.38.0=h516909a_1003
  - plotly=4.9.0=pyh9f0ad1d_0
  - plotly-orca=3.4.2=0
  - pluggy=0.13.1=py37hc8dfbb8_2
  - poppler=0.65.0=h14e79db_0
  - poppler-data=0.4.9=1
  - pre-commit=2.9.0=py37h89c1867_0
  - prettytable=0.7.2=py_3
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.7=py_0
  - psutil=5.7.2=py37h8f50634_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=pyh9f0ad1d_0
  - pybedtools=0.8.1=py37h8270d21_2
  - pybigwig=0.3.17=py37h960e705_2
  - pycodestyle=2.6.0=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydna=3.0.2=py_0
  - pydot=1.4.1=py37hc8dfbb8_1002
  - pyfaidx=0.5.9.1=pyh864c0ab_1
  - pyflakes=2.2.0=py_0
  - pygments=2.7.1=py_0
  - pygraphviz=1.6=py37h8f50634_0
  - pylint=2.6.0=py37hc8dfbb8_1
  - pymysql=0.10.0=pyh9f0ad1d_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h8f50634_0
  - pysam=0.16.0.1=py37hc334e0b_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pytest=6.1.0=py37hc8dfbb8_0
  - python=3.7.8=h6f2ec95_1_cpython
  - python-dateutil=2.8.1=py_0
  - python-wget=3.2=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py37hb5d75c8_1
  - pyzmq=19.0.2=py37hac76be4_0
  - r-askpass=1.1=r36hcdcec82_2
  - r-assertthat=0.2.1=r36h6115d3f_2
  - r-backports=1.1.10=r36hcdcec82_0
  - r-base=3.6.3=he766273_3
  - r-base64enc=0.1_3=r36hcdcec82_1004
  - r-bh=1.72.0_3=r36h6115d3f_1
  - r-biocmanager=1.30.10=r36h6115d3f_1
  - r-bit=4.0.4=r36hcdcec82_0
  - r-bit64=4.0.5=r36hcdcec82_0
  - r-blob=1.2.1=r36h6115d3f_1
  - r-boot=1.3_25=r36h6115d3f_1
  - r-broom=0.7.0=r36h6115d3f_0
  - r-callr=3.4.4=r36h6115d3f_0
  - r-caret=6.0_86=r36hcdcec82_2
  - r-cellranger=1.1.0=r36h6115d3f_1003
  - r-class=7.3_17=r36hcdcec82_1
  - r-cli=2.0.2=r36h6115d3f_1
  - r-clipr=0.7.0=r36h6115d3f_1
  - r-cluster=2.1.0=r36h9bbef5b_3
  - r-codetools=0.2_16=r36h6115d3f_1002
  - r-colorspace=1.4_1=r36hcdcec82_2
  - r-commonmark=1.7=r36hcdcec82_1002
  - r-cowplot=1.1.0=r36h6115d3f_0
  - r-crayon=1.3.4=r36h6115d3f_1003
  - r-curl=4.3=r36hcdcec82_1
  - r-data.table=1.12.8=r36hcdcec82_1
  - r-dbi=1.1.0=r36h6115d3f_1
  - r-dbplyr=1.4.4=r36h6115d3f_0
  - r-desc=1.2.0=r36h6115d3f_1003
  - r-digest=0.6.25=r36h0357c0b_2
  - r-dplyr=1.0.2=r36h0357c0b_0
  - r-ellipsis=0.3.1=r36hcdcec82_0
  - r-essentials=3.6.0=r36_0
  - r-europepmc=0.4=r36h6115d3f_0
  - r-evaluate=0.14=r36h6115d3f_2
  - r-fansi=0.4.1=r36hcdcec82_1
  - r-farver=2.0.3=r36h0357c0b_1
  - r-fastmap=1.0.1=r36h0357c0b_1
  - r-fastmatch=1.1_0=r36hcdcec82_1005
  - r-forcats=0.5.0=r36h6115d3f_1
  - r-foreach=1.5.0=r36h6115d3f_1
  - r-foreign=0.8_71=r36h96ca727_0
  - r-formatr=1.7=r36h6115d3f_2
  - r-fs=1.5.0=r36h0357c0b_0
  - r-futile.logger=1.4.3=r36h6115d3f_1003
  - r-futile.options=1.0.1=r36h6115d3f_1002
  - r-generics=0.0.2=r36h6115d3f_1003
  - r-ggforce=0.3.2=r36h0357c0b_0
  - r-ggplot2=3.3.2=r36h6115d3f_0
  - r-ggplotify=0.0.5=r36h6115d3f_1
  - r-ggraph=2.0.3=r36h0357c0b_0
  - r-ggrepel=0.8.2=r36h0357c0b_1
  - r-ggridges=0.5.2=r36h6115d3f_2
  - r-glmnet=4.0_2=r36h9bbef5b_0
  - r-glue=1.4.2=r36hcdcec82_0
  - r-gower=0.2.2=r36hcdcec82_0
  - r-graphlayouts=0.7.0=r36h0357c0b_1
  - r-gridextra=2.3=r36h6115d3f_1003
  - r-gridgraphics=0.5_0=r36h6115d3f_1
  - r-gtable=0.3.0=r36h6115d3f_3
  - r-haven=2.3.1=r36hde08347_0
  - r-hexbin=1.28.1=r36h9bbef5b_1
  - r-highr=0.8=r36h6115d3f_2
  - r-hms=0.5.3=r36h6115d3f_1
  - r-htmltools=0.5.0=r36h0357c0b_0
  - r-htmlwidgets=1.5.1=r36h6115d3f_1
  - r-httpuv=1.5.4=r36h0357c0b_0
  - r-httr=1.4.2=r36h6115d3f_0
  - r-igraph=1.2.5=r36hd626d4e_1
  - r-ipred=0.9_9=r36hcdcec82_2
  - r-irdisplay=0.7=r36_1002
  - r-irkernel=1.1.1=r36h6115d3f_0
  - r-isoband=0.2.2=r36h0357c0b_0
  - r-iterators=1.0.12=r36h6115d3f_1
  - r-jsonlite=1.7.1=r36hcdcec82_0
  - r-kernsmooth=2.23_17=r36hfa343cc_1
  - r-knitr=1.30=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_1003
  - r-lambda.r=1.2.4=r36h6115d3f_1
  - r-later=1.1.0.1=r36h0357c0b_0
  - r-lattice=0.20_41=r36hcdcec82_2
  - r-lava=1.6.8=r36h6115d3f_0
  - r-lifecycle=0.2.0=r36h6115d3f_1
  - r-lubridate=1.7.9=r36h0357c0b_0
  - r-magrittr=1.5=r36h6115d3f_1003
  - r-maps=3.3.0=r36hcdcec82_1004
  - r-markdown=1.1=r36hcdcec82_1
  - r-mass=7.3_53=r36hcdcec82_0
  - r-matrix=1.2_18=r36h7fa42b6_3
  - r-memoise=1.1.0=r36h6115d3f_1004
  - r-mgcv=1.8_33=r36h7fa42b6_0
  - r-mime=0.9=r36hcdcec82_1
  - r-modelmetrics=1.2.2.2=r36h0357c0b_1
  - r-modelr=0.1.8=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_1003
  - r-nlme=3.1_149=r36h9bbef5b_0
  - r-nnet=7.3_14=r36hcdcec82_1
  - r-numderiv=2016.8_1.1=r36h6115d3f_3
  - r-openssl=1.4.3=r36he5c4762_0
  - r-pbdzmq=0.3_3=r36h559a7a4_1003
  - r-pillar=1.4.6=r36h6115d3f_0
  - r-pkgbuild=1.1.0=r36h6115d3f_0
  - r-pkgconfig=2.0.3=r36h6115d3f_1
  - r-pkgload=1.1.0=r36h0357c0b_0
  - r-plogr=0.2.0=r36h6115d3f_1003
  - r-plyr=1.8.6=r36h0357c0b_1
  - r-polyclip=1.10_0=r36h0357c0b_2
  - r-praise=1.0.0=r36h6115d3f_1004
  - r-prettyunits=1.1.1=r36h6115d3f_1
  - r-proc=1.16.2=r36h0357c0b_1
  - r-processx=3.4.4=r36hcdcec82_0
  - r-prodlim=2019.11.13=r36h0357c0b_1
  - r-progress=1.2.2=r36h6115d3f_2
  - r-promises=1.1.1=r36h0357c0b_0
  - r-ps=1.3.4=r36hcdcec82_0
  - r-purrr=0.3.4=r36hcdcec82_1
  - r-quantmod=0.4.17=r36h6115d3f_1
  - r-r6=2.4.1=r36h6115d3f_1
  - r-randomforest=4.6_14=r36h9bbef5b_1003
  - r-rbokeh=0.6.3=r36_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1003
  - r-rcpp=1.0.5=r36h0357c0b_0
  - r-rcpparmadillo=0.9.900.3.0=r36h51c796c_0
  - r-rcppeigen=0.3.3.7.0=r36h51c796c_2
  - r-readr=1.3.1=r36h0357c0b_1004
  - r-readxl=1.3.1=r36hde08347_4
  - r-recipes=0.1.13=r36h6115d3f_0
  - r-recommended=3.6.0=r36_0
  - r-rematch=1.0.1=r36h6115d3f_1003
  - r-repr=1.1.0=r36h6115d3f_1
  - r-reprex=0.3.0=r36h6115d3f_2
  - r-reshape2=1.4.4=r36h0357c0b_1
  - r-rlang=0.4.7=r36hcdcec82_0
  - r-rmarkdown=2.4=r36h142f84f_0
  - r-rpart=4.1_15=r36hcdcec82_2
  - r-rprojroot=1.3_2=r36h6115d3f_1003
  - r-rsqlite=2.2.1=r36h1b71b39_0
  - r-rstudioapi=0.11=r36h6115d3f_1
  - r-rvcheck=0.1.8=r36h6115d3f_1
  - r-rvest=0.3.6=r36h6115d3f_0
  - r-scales=1.1.1=r36h6115d3f_0
  - r-selectr=0.4_2=r36h6115d3f_1
  - r-shape=1.4.5=r36_0
  - r-shiny=1.5.0=r36h6115d3f_0
  - r-snow=0.4_3=r36h6115d3f_1002
  - r-sourcetools=0.1.7=r36he1b5a44_1002
  - r-spatial=7.3_12=r36hcdcec82_1
  - r-squarem=2020.4=r36h6115d3f_0
  - r-stringi=1.5.3=r36h604b29c_0
  - r-stringr=1.4.0=r36h6115d3f_2
  - r-survival=3.2_7=r36hcdcec82_0
  - r-sys=3.4=r36hcdcec82_0
  - r-testthat=2.3.2=r36h0357c0b_1
  - r-tibble=3.0.3=r36hcdcec82_0
  - r-tidygraph=1.2.0=r36h0357c0b_0
  - r-tidyr=1.1.2=r36h0357c0b_0
  - r-tidyselect=1.1.0=r36h6115d3f_0
  - r-tidyverse=1.3.0=r36h6115d3f_2
  - r-timedate=3043.102=r36h6115d3f_1002
  - r-tinytex=0.26=r36h6115d3f_0
  - r-triebeard=0.3.0=r36he1b5a44_1003
  - r-ttr=0.24.2=r36hcdcec82_0
  - r-tweenr=1.0.1=r36h0357c0b_1002
  - r-urltools=1.7.3=r36h0357c0b_2
  - r-utf8=1.1.4=r36hcdcec82_1003
  - r-uuid=0.1_4=r36hcdcec82_1
  - r-vctrs=0.3.4=r36hcdcec82_0
  - r-viridis=0.5.1=r36h6115d3f_1004
  - r-viridislite=0.3.0=r36h6115d3f_1003
  - r-whisker=0.4=r36h6115d3f_1
  - r-withr=2.3.0=r36h6115d3f_0
  - r-xfun=0.18=r36hcdcec82_0
  - r-xml=3.98_1.19=r36h96ca727_0
  - r-xml2=1.3.2=r36h0357c0b_1
  - r-xtable=1.8_4=r36h6115d3f_3
  - r-xts=0.12.1=r36hcdcec82_0
  - r-yaml=2.2.1=r36hcdcec82_1
  - r-zeallot=0.1.0=r36h6115d3f_1002
  - r-zoo=1.8_8=r36hcdcec82_0
  - readline=8.0=he28a2e2_2
  - regex=2020.11.13=py37h4abf009_0
  - requests=2.24.0=pyh9f0ad1d_0
  - retrying=1.3.3=py_2
  - samtools=1.10=h2e538c0_3
  - scikit-bio=0.5.6=py37h03ebfcd_2
  - scikit-learn=0.23.2=py37h6785257_0
  - scipy=1.5.2=py37hb14ef9d_0
  - seaborn=0.10.1=py_0
  - sed=4.8=hbfbb72e_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37hc8dfbb8_1
  - simplejson=3.17.2=py37h8f50634_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h4cf870e_0
  - statsmodels=0.12.0=py37h8f50634_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tabulate=0.8.7=pyh9f0ad1d_0
  - terminado=0.9.1=py37hc8dfbb8_0
  - testpath=0.4.4=py_0
  - texlive-core=20180414=pl526hc0a3334_3
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - toml=0.10.1=pyh9f0ad1d_0
  - tornado=6.0.4=py37h8f50634_1
  - traitlets=5.0.4=py_1
  - tspex=0.6.2=py_0
  - typed-ast=1.4.1=py37h4abf009_1
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.10=py_0
  - virtualenv=20.2.1=py37h89c1867_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - wrapt=1.11.2=py37h8f50634_1
  - xarray=0.16.1=py_0
  - xlrd=1.2.0=pyh9f0ad1d_1
  - xlsxwriter=1.3.6=pyh9f0ad1d_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.3=he1b5a44_0
  - zipp=3.2.0=py_0
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - beautifulsoup4==4.9.0
    - dna-features-viewer==3.0.1
    - dnacauldron==2.0.1
    - et-xmlfile==1.0.1
    - flametree==0.1.10
    - fuzzywuzzy==0.18.0
    - gat==1.3.6
    - html2text==2020.1.16
    - jdcal==1.4.1
    - openpyxl==3.0.4
    - overleaf-sync==1.0.3
    - proglog==0.1.9
    - python-levenshtein==0.12.0
    - researchpy==0.1.9
    - scikit-posthocs==0.6.4
    - snapgene-reader==0.1.17
    - soupsieve==2.0
    - statannot==0.2.3
    - tqdm==4.47.0
    - xlwt==1.3.0
    - xmltodict==0.12.0
    - yaspin==0.16.0
prefix: /home/witham/opt/anaconda3/envs/PromoterArchitecturePipeline
